DATASETS:
  CLASS_IDS: '[0,1]'
  TRAIN: mnist
DEBUG: 0
MODEL:
  INITIALIZATION: xavier
  INIT_FACTOR: 1.0
  LAYER_LIST: '[''conv_1_128_5'', ''batchnorm2D_128'', ''relu'', ''conv_128_256_3'',
    ''avgpool'', ''linear_256_10'']'
  SAVE_START: 20
  TYPE: MLP3
NAME: mnist
OUTPUT_DIR: results/output_5/train
SEED: -1
SOLVER:
  BASE_LR: 0.001
  BATCH_SIZE: 300
  BATCH_SIZE_VAL: 100
  EPOCHS: 40
  GPUS:
  - 5
  MILESTONE:
  - 10
  - 20
  MOMENTUM: 0.9
  NUM_WORKERS: 8
  WEIGHT_DECAY: 0.0005
TEMP_DIR: results/output_5/temp
WANDB:
  ENABLE: false
  ENTITY: pinlab-sapienza
  GROUP: MNIST
  PROJECT: param_text_align
resume: ''
