WANDB:
  ENABLE: False
  GROUP: "VAE"
  PROJECT: "param_text_align"
  ENTITY: "pinlab-sapienza"

DATASETS:
  TRAIN: "results/all_linear_pretrained/mnist"   # results/pretrained_models/ mnist, cifar10, cifar100, imagenette, imagenet
  VALID: "results/all_linear_validation/mnist"

SOLVER:
 GPUS: [0]
 NUM_WORKERS: 8
 BASE_LR: 1e-4
 BATCH_SIZE: 1
 EPOCHS: 100
#  LR_METHOD: "poly"
#  LR_POWER: 0.5
#  MOMENTUM: 0.9
 WEIGHT_DECAY: 0.0005
 ETA_MIN: 1e-7
#  WARMUP_ITERS: 200
 BATCH_SIZE_VAL: 1


NAME: "mnist_correct_val"
OUTPUT_DIR: "results/vae_mnist/"
resume: ""
SEED: -1
DEBUG: 0