wandb_version: 1

DATASETS:
  desc: null
  value:
    TEST: datasets/valid/
    TRAIN: datasets/mnist/
DEBUG:
  desc: null
  value: 0
INPUT:
  desc: null
  value:
    IN_CHANNELS: 1
    OUT_CHANNELS: 1
    SIZE:
    - 10
    - 785
MODEL:
  desc: null
  value:
    NAME: deeplabv3plus_resnet101
    NUM_CLASSES: 18
    OUTPUT_DIM: 64
NAME:
  desc: null
  value: mnist
OUTPUT_DIR:
  desc: null
  value: results/debug
SAVE_DIR:
  desc: null
  value: results/debug/mnist
SEED:
  desc: null
  value: -1
SOLVER:
  desc: null
  value:
    BASE_LR: 0.001
    BASE_LR1: 0.001
    BASE_LR2: 0.0
    BATCH_SIZE: 8
    BATCH_SIZE_VAL: 1
    EPOCHS: 2000
    GPUS:
    - 0
    LR_METHOD: poly
    LR_POWER: 0.5
    MILESTONE:
    - 10
    - 20
    MOMENTUM: 0.9
    NUM_WORKERS: 4
    WARMUP_ITERS: 600
    WEIGHT_DECAY: 0.0005
TEST:
  desc: null
  value:
    BATCH_SIZE: 1
WANDB:
  desc: null
  value:
    ENABLE: true
    ENTITY: pinlab-sapienza
    GROUP: MNIST
    PROJECT: PuzzLayer
_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.15.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: train_acc
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_acc
      5: 1
      6:
      - 1
    python_version: 3.8.17
    start_time: 1718267847
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 77
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 77
      3:
      - 7
      - 13
      - 16
      4: 3.8.17
      5: 0.12.21
      6: 4.15.0
      8:
      - 5
resume:
  desc: null
  value: ''
