MODEL:
  TEXT_INPUT_DIM: 64
  MODEL_INPUT_DIM: 64
  MODEL_OUTPUT_DIM: 64
  PROJ_OUTPUT_DIM: 64
  DROPOUT: 0.1

WANDB:
  ENABLE: False
  GROUP: "alignment"
  PROJECT: "PuzzLayer"
  ENTITY: "pinlab-sapienza"

DATASETS:
  TRAIN: "datasets/trainNEWSMALLER/"   # mnist, cifar10, cifar100, imagenette, imagenet
  TEST: "datasets/validNEW/"

SOLVER:
#  GPUS: [2,3]
 GPU_TEST: [2]
 NUM_WORKERS: 4
#  BASE_LR1: 0.0001
#  BASE_LR2: 0. #0.0001
#  BATCH_SIZE: 64
 EPOCHS: 30000
#  WEIGHT_DECAY: 0. #0.0005
 BATCH_SIZE_VAL: 30
 

NAME: "nothingpre_2gpu" # "dgx_pretrained_moretext_lr5e-4_nowd_64batch_1gpu"
OUTPUT_DIR: "results/debug"
PRETRAINED_MODEL_ENCODER: None #"results/debug/text_lr5e-4_nowd/_val_acc=1.000.ckpt"
MODEL_TO_TEST: "results/debug/modelpre_fullsubset_2gpu_textalsolay/_val_recall_t2i@1=0.864.ckpt"
SAVE_CHECK_EVERY: 200
resume: ""
SEED: -1
DEBUG: 0