MODEL:
  OUTPUT_DIM: 64
  NUM_CLASSES: 10

WANDB:
  ENABLE: True
  GROUP: "alignment"
  PROJECT: "PuzzLayer"
  ENTITY: "pinlab-sapienza"

DATASETS:
  TRAIN: "datasets/trainNEWSMALLER/"   # mnist, cifar10, cifar100, imagenette, imagenet
  TEST: "datasets/validNEW/"

SOLVER:
 GPUS: [4,5,6,7]
 NUM_WORKERS: 4
 BASE_LR1: 0.0005
 BASE_LR2: 0. #0.0001
 MILESTONE: [10,20]
 BATCH_SIZE: 64
 EPOCHS: 30000
 WEIGHT_DECAY: 0. #0.0005
 MOMENTUM: 0.9
#  LR_METHOD: "poly"
#  LR_POWER: 0.5
#  MOMENTUM: 0.9
#  ETA_MIN: 1e-7
#  WARMUP_ITERS: 60
 BATCH_SIZE_VAL: 30
 

NAME: "pretrained_lr5e-4_nowd_64batch_4gpu"
OUTPUT_DIR: "results/debug"
PRETRAINED_MODEL_ENCODER: "results/debug/dgx lr 5e-4 no wd/_val_acc=0.830.ckpt" # None
SAVE_CHECK_EVERY: 200
resume: ""
SEED: -1
DEBUG: 0