MODEL:
  OUTPUT_DIM: 64
  NUM_CLASSES: 10

WANDB:
  ENABLE: True
  GROUP: "MNIST"
  PROJECT: "PuzzLayer"
  ENTITY: "pinlab-sapienza"

DATASETS:
  TRAIN: "datasets/trainMLPSUBSET/"   # mnist, cifar10, cifar100, imagenette, imagenet
  TEST: "datasets/validMLP/"

SOLVER:
 GPUS: [4,5]
 NUM_WORKERS: 4
 BASE_LR1: 0.001 #0.001
 BASE_LR2: 0. #0.0001
 MILESTONE: [10,20]
 BATCH_SIZE: 32
 EPOCHS: 30000
 WEIGHT_DECAY: 0. #0.0005
 MOMENTUM: 0.9
#  LR_METHOD: "poly"
#  LR_POWER: 0.5
#  MOMENTUM: 0.9
#  ETA_MIN: 1e-7
#  WARMUP_ITERS: 60
 BATCH_SIZE_VAL: 1
 

NAME: "mlpsubset_oldhead_lr1e-3"
OUTPUT_DIR: "results/debug"
PRETRAINED_MODEL_ENCODER: None # "results/debug/newhead_lr5e-4_nowd/model_999.ckpt"
SAVE_CHECK_EVERY: 500
resume: ""
SEED: -1
DEBUG: 0