MODEL:
  OUTPUT_DIM: 64
  NUM_CLASSES: 10
  MAKE_TEXT_HEAD: False
  MAKE_MODEL_ENCODER_HEAD: False
  OUTPUT_DIM_HEAD: 64

WANDB:
  ENABLE: False
  GROUP: "alignment"
  PROJECT: "PuzzLayer"
  ENTITY: "pinlab-sapienza"

DATASETS:
  TRAIN: "datasets/trainNEWSMALLER/"   # mnist, cifar10, cifar100, imagenette, imagenet
  TEST: "datasets/validNEW/"

SOLVER:
 GPUS: [2]
 NUM_WORKERS: 4
 BASE_LR1: 0.001
 BASE_LR2: 0. #0.0001
 MILESTONE: [10,20]
 BATCH_SIZE: 100
 EPOCHS: 30000
 WEIGHT_DECAY: 0. #0.0005
 MOMENTUM: 0.9
#  LR_METHOD: "poly"
#  LR_POWER: 0.5
#  MOMENTUM: 0.9
#  ETA_MIN: 1e-7
#  WARMUP_ITERS: 60
 BATCH_SIZE_VAL: 30
 

NAME: "FullText_align_1gpu"
OUTPUT_DIR: "results/debug"
PRETRAINED_MODEL_ENCODER: False #"results/debug/dgx_lr5e-4_nowd/_val_acc=0.877.ckpt" # None
SAVE_CHECK_EVERY: 200
resume: ""
SEED: -1
DEBUG: 0