MODEL:
  OUTPUT_DIM: 64

WANDB:
  ENABLE: False
  GROUP: "MNIST"
  PROJECT: "PuzzLayer"
  ENTITY: "pinlab-sapienza"

DATASETS:
  TRAIN: "datasets/temp_debug/"   # mnist, cifar10, cifar100, imagenette, imagenet

SOLVER:
 GPUS: [3]
 NUM_WORKERS: 8
 BASE_LR: 0.1
 MILESTONE: [10,20]
 BATCH_SIZE: 2
 EPOCHS: 2000
 WEIGHT_DECAY: 0.0005
 MOMENTUM: 0.9
#  LR_METHOD: "poly"
#  LR_POWER: 0.5
#  MOMENTUM: 0.9
#  ETA_MIN: 1e-7
#  WARMUP_ITERS: 200
 BATCH_SIZE_VAL: 2
 

NAME: "mnist"
OUTPUT_DIR: "results/debug"
resume: ""
SEED: -1
DEBUG: 0