MODEL:
  OUTPUT_DIM: 64

WANDB:
  ENABLE: True
  GROUP: "MNIST"
  PROJECT: "PuzzLayer"
  ENTITY: "pinlab-sapienza"

DATASETS:
  TRAIN: "datasets/mnist/"   # mnist, cifar10, cifar100, imagenette, imagenet
  TEST: "datasets/valid/"

SOLVER:
 GPUS: [0]
 NUM_WORKERS: 4
 BASE_LR1: 0.001 #0.0001
 BASE_LR2: 0. #0.0001
 MILESTONE: [10,20]
 BATCH_SIZE: 8
 EPOCHS: 2000
 WEIGHT_DECAY: 0.0005
 MOMENTUM: 0.9
#  LR_METHOD: "poly"
#  LR_POWER: 0.5
#  MOMENTUM: 0.9
#  ETA_MIN: 1e-7
#  WARMUP_ITERS: 60
 BATCH_SIZE_VAL: 1
 

NAME: "mnist"
OUTPUT_DIR: "results/debug"
resume: ""
SEED: -1
DEBUG: 0