MODEL:
  TEXT_INPUT_DIM: 64
  MODEL_INPUT_DIM: 64
  MODEL_OUTPUT_DIM: 64
  PROJ_OUTPUT_DIM: 64
  DROPOUT: 0.1

WANDB:
  ENABLE: True
  GROUP: "alignment"
  PROJECT: "PuzzLayer"
  ENTITY: "pinlab-sapienza"

DATASETS:
  TRAIN: "datasets/trainNEWSMALLER/"   # mnist, cifar10, cifar100, imagenette, imagenet
  TEST: "datasets/validNEW/"

SOLVER:
 GPUS: [5,6]
 NUM_WORKERS: 4
 MODEL_ENCODER_LR: 0.0005
 TEXT_ENCODER_LR: 0.0005
 PROJ_LR: 0.0005
 BATCH_SIZE: 105
 EPOCHS: 30000
 WEIGHT_DECAY: 0. #0.0005
 BATCH_SIZE_VAL: 30
 

NAME: "modelpre_fullsubset_2gpu_textalsolay"
OUTPUT_DIR: "results/debug"
PRETRAINED_MODEL_ENCODER: "results/debug/dgx lr 5e-4 no wd/_val_acc=0.830.ckpt"
SAVE_CHECK_EVERY: 200
resume: ""
SEED: -1
DEBUG: 0