MODEL:
  OUTPUT_DIM: 64
  NUM_CLASSES: 10

WANDB:
  ENABLE: True
  GROUP: "MNIST"
  PROJECT: "PuzzLayer"
  ENTITY: "pinlab-sapienza"

DATASETS:
  TRAIN: "datasets/trainNEWSMALLER/"   # mnist, cifar10, cifar100, imagenette, imagenet
  TEST: "datasets/validNEW/"

SOLVER:
 GPUS: [2,3]
 NUM_WORKERS: 3
 BASE_LR1: 0.0005 #0.001
 BASE_LR2: 0. #0.0001
 MILESTONE: [10,20]
 BATCH_SIZE: 64
 EPOCHS: 30000
 WEIGHT_DECAY: 0. #0.0005
 MOMENTUM: 0.9
#  LR_METHOD: "poly"
#  LR_POWER: 0.5
#  MOMENTUM: 0.9
#  ETA_MIN: 1e-7
#  WARMUP_ITERS: 60
 BATCH_SIZE_VAL: 1
 

NAME: "dgx_lr5e-4_nowd_30kepochs"
OUTPUT_DIR: "results/debug"
SAVE_CHECK_EVERY: 200
resume: ""
SEED: -1
DEBUG: 0